{
 "title": "FastAPI Observability Dashboard",
 "tags": [
  "fastapi",
  "opentelemetry"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Request Duration (ms) - P95",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket[1m])) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Error Count",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_errors_total[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Request Count by Route",
   "type": "graph",
   "gridPos": { "x": 0, "y": 9, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}