global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']

  - job_name: 'orders-service'
    static_configs:
      - targets: ['orders-service:8002']

  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments-service:8003']

